platform :ios, '12.0'
use_frameworks!

target 'MGVideoPlayerKit_Example' do
  pod 'MGVideoPlayerKit', :path => '../'
  pod 'MGTemplateKit', :git => 'https://haraldbregu:4a4d1162147e80549f22cafb59060bdf59c4934a@github.com/HaraldBregu/MGTemplateKit.git'
  pod 'Cosmos', '~> 18.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end
